# Generated by Django 4.0.3 on 2022-03-04 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esp_data_collector', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reading',
            old_name='vlotage',
            new_name='voltage',
        ),
    ]
