# Generated by Django 4.0.3 on 2022-03-15 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esp_data_collector', '0002_esp_reading_delete_reading'),
        ('esp_data_collector', '0002_rename_vlotage_reading_voltage'),
    ]

    operations = [
    ]
