# Generated by Django 4.0.3 on 2022-03-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp_data_collector', '0003_merge_20220315_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.FloatField()),
                ('voltage', models.FloatField()),
                ('wattage', models.FloatField()),
                ('temperature', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='esp_reading',
        ),
    ]
