# Generated by Django 4.0.3 on 2022-03-15 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('esp_data_collector', '0004_reading_delete_esp_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
